@startuml 

skinparam shadowing true

title Бронирование переговорки (создание + отмена)

start
:Пользователь открывает сервис переговорок;
if (Что делает пользователь?) then (Создает\n бронь)
:Ввести дату/время начала/время конца/участников;
:Система показывает доступные комнаты;
:Пользователь выбирает комнату;
:Проверка ограничений\n (время корректно, длительность ≤ 2ч, не больше 3 активных броней);
    if (Ограничения нарушены?) then (Да)
    :Показать ошибку;
    stop
    else (Нет)
        if (комната занята?) then (Да)
        :Показать “занято, выбери другое”;
        stop
        else (Нет)
        :Создать бронь в БД статус BOOKED;
        :Отправить уведомления участникам;
        stop
        endif
    endif
else (Отменяет бронь)
:Открыть “Мои брони”;
:Выбрать бронь;
:Нажать “Отменить”;
    if (До начала < 10 минут?) then (Да)
    :Показать “поздно отменять нельзя”;
    stop
    else (Нет)
    :Обновить статус CANCELLED;
    :Отправить уведомления участникам;
    stop
    endif
endif

@enduml
